"""Fail fast when the buildless public site drifts or loses basic semantics."""

from __future__ import annotations

import json
import re
from html.parser import HTMLParser
from pathlib import Path

HERE = Path(__file__).resolve().parent
SITE = HERE / "site"
EXPECTED_FILES = {
    "app.js",
    "content.js",
    "index.html",
    "playground.html",
    "release.json",
    "release.schema.json",
    "styles.css",
}


class SiteParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.elements: list[tuple[str, dict[str, str | None]]] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        self.elements.append((tag, dict(attrs)))


def main() -> int:
    # The whole deploy root is uploaded, including subdirectories. Counting only
    # top-level regular files lets an accidental backup/ or stores/ directory pass.
    entries = list(SITE.iterdir())
    files = {path.name for path in entries}
    assert files == EXPECTED_FILES, f"unexpected deploy surface: {sorted(files)}"
    assert all(path.is_file() and not path.is_symlink() for path in entries), (
        "deploy entries must be regular files, not directories or symlinks"
    )

    index = (SITE / "index.html").read_text(encoding="utf-8")
    parser = SiteParser()
    parser.feed(index)

    elements = parser.elements
    ids = [attrs["id"] for _, attrs in elements if attrs.get("id")]
    assert len(ids) == len(set(ids)), "duplicate id in index.html"
    assert sum(tag == "h1" for tag, _ in elements) == 1, "the page needs exactly one h1"
    assert any(tag == "main" for tag, _ in elements), "missing main landmark"

    labels = {attrs.get("for") for tag, attrs in elements if tag == "label" and attrs.get("for")}
    fields = {
        attrs["id"]
        for tag, attrs in elements
        if tag in {"input", "textarea", "select"} and attrs.get("id")
    }
    assert fields <= labels, f"fields without associated labels: {sorted(fields - labels)}"

    for tag, attrs in elements:
        if "data-zh" in attrs:
            assert "data-en" in attrs, f"{tag} has Chinese copy without English copy"
        if "data-placeholder-zh" in attrs:
            assert "data-placeholder-en" in attrs, f"{tag} has an unpaired translated placeholder"
        if "data-aria-zh" in attrs:
            assert "data-aria-en" in attrs, f"{tag} has an unpaired translated accessible name"
        if "data-requires-live" in attrs:
            assert "disabled" in attrs, f"{tag} live control is enabled before session issuance"

    status = next(attrs for _, attrs in elements if attrs.get("id") == "statusText")
    assert status.get("aria-live") == "polite", "engine status changes are not announced"
    assert "560 tests" not in index and "six endpoints" not in index
    assert "hard-deleted after 60 minutes" not in index, (
        "site over-promises restart-durable retention that main does not provide"
    )
    assert "not a production retention guarantee" in index
    assert any(attrs.get("id") == "releaseMeta" for _, attrs in elements)
    assert any(attrs.get("id") == "releaseCommit" for _, attrs in elements)
    assert any((attrs.get("href") or "").startswith("./release.json") for _, attrs in elements), (
        "release manifest is not linked from the evidence block"
    )

    live_buttons = [attrs for _, attrs in elements if "data-live" in attrs]
    assert live_buttons, "no live scenarios"
    assert all(attrs.get("aria-pressed") == "false" for attrs in live_buttons), (
        "live scenario selection has no initial accessible state"
    )

    # The page answers from retrieval, not from a model: the demo backend carries no
    # provider SDK. Saying so is the difference between a demo and a misrepresentation,
    # so it is required rather than trusted to survive an edit.
    assert "not generated by a model" in index or "不是模型生成" in index, (
        "the page does not say its answers come from retrieval rather than a model"
    )
    assert "no LLM extracts or answers here" in index, (
        "the page does not disclose that the demo does not run the LLM"
    )
    # The headline is one sentence, and the sentence that qualifies it must be present.
    assert any(attrs.get("id") == "headline" for _, attrs in elements), "no headline result"
    assert any(attrs.get("id") == "footnote" for _, attrs in elements), (
        "the headline result has no qualifying footnote"
    )

    for _, attrs in elements:
        asset = attrs.get("href") or attrs.get("src")
        if asset and asset.startswith("./") and not asset.startswith("./#"):
            target = asset.removeprefix("./").split("?", 1)[0].split("#", 1)[0]
            assert (SITE / target).exists(), f"missing local asset: {asset}"

    release = json.loads((SITE / "release.json").read_text(encoding="utf-8"))
    schema = json.loads((SITE / "release.schema.json").read_text(encoding="utf-8"))
    assert release["$schema"] == "./release.schema.json"
    assert schema["properties"]["schema_version"]["const"] == release["schema_version"]
    assert release["schema_version"] == 2
    assert release["release"], "release manifest has no public release id"
    engineering = release["engineering"]
    assert engineering["tests"] > 0
    # Schema 1 counted one case per tracked document inside `tests`, so the figure rose
    # when documents were committed and said nothing about the code. They are separate
    # from schema 2 on, and a page that showed one under the other's label would be
    # restating the same defect in a new place.
    assert engineering["document_checks"] >= 0
    # A figure the public repository cannot reproduce is not publishable. The digest is
    # what lets a reader check that the tree these numbers came from is the tree in front
    # of them — and unlike a commit SHA it survives an amend, a squash or a rebase.
    assert re.fullmatch(r"[0-9a-f]{64}", engineering["measured_tree_sha256"] or ""), (
        "the release manifest has no usable measured-tree digest"
    )
    reference = engineering.get("source_commit_for_reference")
    assert reference is None or re.fullmatch(r"[0-9a-f]{7,40}", reference)
    assert "source_commit" not in engineering, (
        "a bare source_commit invites reliance on a SHA a history rewrite can orphan"
    )

    result = release["result"]
    for key in ("accuracy", "naive_rag_accuracy"):
        assert 0 <= result[key] <= 100, f"{key} is not a percentage"
    assert result["baseline_run_on_heldout"] is False
    # Both arms must come from the same run on the same questions. A headline comparing
    # this system's one-shot result against a baseline measured elsewhere would be the
    # easiest number on the page to get wrong.
    assert result["one_shot"] is True
    assert result["questions"] > 0
    assert result["median_context_tokens"] >= 0
    assert result["naive_rag_median_context_tokens"] >= 0
    # Manifest and schema must agree on the required shape, so a field the page reads
    # cannot quietly disappear.
    for key in schema["properties"]["result"]["required"]:
        assert key in result, f"release manifest is missing required result field {key!r}"

    app = (SITE / "app.js").read_text(encoding="utf-8")
    assert "renderMetrics();" in app, "language changes do not re-render manifest copy"
    # No measured figure may be typed into the page. Everything shown comes from the
    # manifest, which records the commit it was measured at.
    for figure in ("72%", "574", "65%", "12,763", "12763", "109,059"):
        assert figure not in app, f"measured figure {figure!r} hard-coded outside release.json"
        assert figure not in index, f"measured figure {figure!r} hard-coded in index.html"
    # Whether the gap is significant is a claim, so it is driven by the manifest rather
    # than written once and left behind by a future release that is significant.
    assert "significant_vs_naive_rag" in app, (
        "the significance footnote is not driven by the release manifest"
    )
    assert "full_context_accuracy" in app and "vs_naive_rag_p_value" in app, (
        "the comparison or its p-value is missing from the public result"
    )
    assert "median_context_tokens" not in app, (
        "the page must not compare context estimates with provider input tokens"
    )
    scenario_body = re.search(
        r"async function runLiveScenario\(name\) \{(?P<body>.*?)\n\}",
        app,
        re.DOTALL,
    )
    assert scenario_body, "runLiveScenario is missing"
    body = scenario_body.group("body")
    assert body.index('await freshSession("walk");') < body.index("/demo/facts"), (
        "a preset can write facts before receiving a clean namespace"
    )
    # The walkthrough and the visitor's own box must not share a namespace: one would
    # show the other's facts, and re-running the walkthrough would wipe what the visitor
    # had just typed.
    assert 'as: "walk"' in app and 'as: "try"' in app, "the two demos are not namespaced apart"

    css = (SITE / "styles.css").read_text(encoding="utf-8")
    narrow = re.search(r"@media \(max-width: 920px\) \{(?P<body>.*?)\n\}", css, re.DOTALL)
    assert narrow, "no narrow-viewport rules"
    # The two panes must stack rather than shrink. A memory row that wraps mid-key stops
    # reading as a key/value pair, which is the one thing the state panel exists to show.
    assert ".split { grid-template-columns: 1fr; }" in narrow.group("body"), (
        "narrow layout does not stack the conversation and state panes"
    )
    # A retired fact has to look retired, or the page shows a list and claims a timeline.
    assert ".row.superseded" in css, "superseded facts are not visually distinguished"

    content = (SITE / "content.js").read_text(encoding="utf-8")
    assert "WALKTHROUGH" in content and "PATTERNS" in content, "missing scenario exports"
    assert "zh:" in content and "en:" in content
    # The walkthrough's middle turn is a plan, and it must not be written as a
    # replacement: a plan that supersedes a fact is the defect the example demonstrates.
    plan_turn = re.search(
        r'predicate:\s*"plans_move_to".*?replaces_previous:\s*(?P<flag>true|false)',
        content,
        re.DOTALL,
    )
    assert plan_turn and plan_turn.group("flag") == "false", (
        "the walkthrough lets a plan supersede a fact"
    )
    # The box's patterns stand in for the model's verdict on what a statement does to the
    # value before it. For an attribute that holds one value at a time the product's keying
    # prompt says `replaces`, so "I live in Sydney" retires "I live in Canberra". Marked
    # `false`, both stayed active and the ranking chose the answer.
    for attribute in ("lives_in", "uses_framework", "works_as", "works_at"):
        flags = re.findall(rf'predicate:\s*"{attribute}",\s*replaces:\s*(true|false)', content)
        assert flags and set(flags) == {"true"}, (
            f"a {attribute} pattern leaves the earlier value active"
        )

    # Remembering across conversations is the headline claim, and the box is where a
    # visitor can check it. A button that only cleared the transcript would stage a new
    # conversation the engine never heard about, so every fact must carry the
    # conversation it was stated in.
    assert any(attrs.get("id") == "tryNewConversation" for _, attrs in elements), (
        "the box has no way to start a new conversation"
    )
    assert re.search(
        r'"/demo/facts",\s*\{\s*\.\.\.fact,\s*session_id:\s*conversationId\(conversation\)\s*\}',
        app,
    ), "facts are not written with the conversation they were stated in"

    # The live pane claims to show what the engine was sent. The engine is sent English,
    # so a translated bubble would misrepresent the request; Chinese belongs in `gloss`.
    sent = re.findall(r'^\s*text:\s*"([^"]*)"', content, re.MULTILINE)
    assert sent, "no live conversation payloads found"
    cjk = [line for line in sent if re.search(r"[\u4e00-\u9fff]", line)]
    assert not cjk, f"live conversation shows text the engine never receives: {cjk}"
    assert "gloss:" in content, "Chinese readers lose the conversation without a gloss"

    print(f"public site OK: {len(files)} deploy files, {len(fields)} labelled fields")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
